const trip = {
  itinerary: [
    ['Wed, Oct 14', 'Day 1', 'Monterey → Carmel', '34 mi · 1h 10m', 'Pick up van · groceries · sunset at Asilomar', 'Veterans Memorial Park', 'Check-in 3:00 PM', 'Site 14 · Example reservation'],
    ['Thu, Oct 15', 'Day 2', 'Carmel → Big Sur', '42 mi · 1h 35m', 'Point Lobos hike · Bixby Bridge · McWay Falls', 'Pfeiffer Big Sur SP', 'Check-in 2:00 PM', 'Site 87 · #EXAMPLE-48291'],
    ['Fri, Oct 16', 'Day 3', 'Explore Big Sur', '28 mi · 55m', 'Morning redwoods · Pfeiffer Beach · stargazing', 'Pfeiffer Big Sur SP', 'Stay night', 'Site 87 · no check-out'],
    ['Sat, Oct 17', 'Day 4', 'Big Sur → San Simeon', '72 mi · 2h 15m', 'Ragged Point · elephant seals · Hearst Castle', 'San Simeon Creek', 'Check-in 2:00 PM', 'Site B-22 · #EXAMPLE-64520'],
    ['Sun, Oct 18', 'Day 5', 'San Simeon → Morro Bay', '36 mi · 1h 30m', 'Moonstone Beach · Morro Rock · return van', 'Homeward bound', 'Van return 5:00 PM', 'Fuel up before return']
  ],
  legs: [['Monterey', 'Carmel-by-the-Sea', '12 mi', '0:30'], ['Carmel', 'Pfeiffer Big Sur SP', '42 mi', '1:35'], ['Big Sur', 'San Simeon', '86 mi', '2:45'], ['San Simeon', 'Morro Bay', '72 mi', '2:35']],
  packing: [['Essentials', 'Driver’s license & insurance card', true], ['Essentials', 'Offline maps & campsite confirmations', true], ['Camp', 'Headlamps + spare batteries', true], ['Camp', 'Camp chairs', false], ['Kitchen', 'Cooler, ice & water jugs', true], ['Kitchen', 'Camp stove + fuel', false], ['Clothing', 'Layers & rain shell', true], ['Clothing', 'Hiking boots', false]],
  reservations: [['Camper van', 'Escape Campervans', 'Confirmed', '#EXAMPLE-1038', 'Paid', 'Pick-up Oct 14 · 10:00 AM', 'https://example.com'], ['Campground', 'Pfeiffer Big Sur SP', 'Confirmed', '#EXAMPLE-48291', 'Paid', 'Cancel by Oct 7', 'https://www.parks.ca.gov'], ['Tour', 'Hearst Castle', 'Confirmed', '#EXAMPLE-64520', 'Due at arrival', 'Oct 17 · 1:20 PM', 'https://hearstcastle.org']],
  budget: [['Fuel', 240, 185, '#d97c55'], ['Camping', 280, 244, '#1f7772'], ['Food & drinks', 340, 286, '#dbad4b'], ['Activities', 210, 180, '#385f65'], ['Miscellaneous', 180, 95, '#a86e85']]
};

const $ = (s) => document.querySelector(s);
function renderItinerary() { $('#itineraryList').innerHTML = trip.itinerary.map((d, i) => `<article class="day-card ${i === 1 ? 'featured' : ''}"><div class="day-date"><span>${d[0]}</span><b>${d[1]}</b></div><div class="day-main"><h3>${d[2]}</h3><p class="miles">↝ ${d[3]}</p><p>${d[4]}</p></div><div class="stay"><span class="eyebrow">Tonight</span><strong>${d[5]}</strong><p>${d[6]}<br />${d[7]}</p></div></article>`).join(''); }
function renderRoute() { $('#routeLegs').innerHTML = trip.legs.map((l, i) => `<div class="route-leg"><span class="leg-num">0${i + 1}</span><div><strong>${l[0]} <i>→</i> ${l[1]}</strong><p>${i === 1 ? 'Bixby Bridge + McWay Falls' : i === 2 ? 'Scenic Highway 1' : 'Coastal drive'}</p></div><span>${l[2]}<small>${l[3]}</small></span></div>`).join(''); }
function renderPacking() { const done = trip.packing.filter(x => x[2]).length, percent = Math.round(done / trip.packing.length * 100), circle = $('#packingProgress'); circle.style.setProperty('--progress', `${percent * 3.6}deg`); circle.querySelector('span').textContent = `${percent}%`; let last = ''; $('#packingList').innerHTML = trip.packing.map((x, i) => { const label = x[0] !== last ? `<h3>${x[0]}</h3>` : ''; last = x[0]; return `${label}<label class="check-row"><input type="checkbox" data-index="${i}" ${x[2] ? 'checked' : ''}/><span></span>${x[1]}</label>`; }).join(''); document.querySelectorAll('.check-row input').forEach(el => el.addEventListener('change', e => { trip.packing[e.target.dataset.index][2] = e.target.checked; renderPacking(); })); }
function renderReservations() { $('#reservationList').innerHTML = trip.reservations.map(r => `<article class="reservation"><div class="reservation-icon">${r[0] === 'Camper van' ? '▱' : r[0] === 'Campground' ? '⌂' : '◒'}</div><div><p class="eyebrow">${r[0]} <b class="status">${r[2]}</b></p><h3>${r[1]}</h3><p>${r[5]}<br /><span>${r[3]} · ${r[4]}</span></p></div><a href="${r[6]}" target="_blank" rel="noreferrer" aria-label="Open reservation">↗</a></article>`).join(''); }
function renderBudget() { const totalPlan = trip.budget.reduce((a,b) => a+b[1],0), totalSpent = trip.budget.reduce((a,b) => a+b[2],0); $('#budgetTable').innerHTML = `<div class="budget-row budget-labels"><span>Category</span><span>Planned</span><span>Spent</span><span>Remaining</span></div>` + trip.budget.map(x => { const remainder = x[1]-x[2]; return `<div class="budget-row"><span class="category"><i style="background:${x[3]}"></i>${x[0]}</span><span>$${x[1]}</span><span>$${x[2]}</span><span class="${remainder < 0 ? 'over' : ''}">$${remainder}</span><div class="mini-bar"><i style="width:${Math.min(x[2]/x[1]*100,100)}%;background:${x[3]}"></i></div></div>`; }).join('') + `<div class="budget-row total"><span>Total</span><span>$${totalPlan}</span><span>$${totalSpent}</span><span>$${totalPlan-totalSpent}</span></div>`; }
function renderCalendar() { const cal = $('#calendar'), days = []; for(let i=0;i<3;i++) days.push('<div class="empty"></div>'); for(let d=1;d<=31;d++) { const tripDay = d >= 14 && d <= 18; const type = d === 14 || d === 18 ? 'drive' : tripDay ? 'stay' : d === 17 ? 'event' : ''; const note = ({14:'Van pickup',15:'Big Sur',16:'Hike day',17:'Hearst Castle',18:'Return van'})[d] || ''; days.push(`<div class="cal-day ${type}"><b>${d}</b>${note ? `<span>${note}</span>` : ''}</div>`); } cal.innerHTML = days.join(''); }
renderItinerary(); renderRoute(); renderPacking(); renderReservations(); renderBudget(); renderCalendar();
const departure = new Date('2026-10-14T09:00:00'); const days = Math.ceil((departure - new Date()) / 86400000); $('#countdown').textContent = days > 0 ? `${days} days to go` : 'Trip time!';
$('#printBtn').addEventListener('click', () => window.print()); $('#editNote').addEventListener('click', () => $('#noteDialog').showModal()); $('#saveNote').addEventListener('click', () => { const note = $('#tripNote').value.trim(); if(note) { localStorage.setItem('big-sur-note', note); $('#editNote').textContent = 'Note saved ✓'; } }); if(localStorage.getItem('big-sur-note')) $('#editNote').textContent = 'Edit saved note';
$('#addExpense').addEventListener('click', () => { const name = prompt('Expense category (example: Groceries)'); const amount = Number(prompt('Amount spent')); if(name && Number.isFinite(amount)) { trip.budget.push([name, amount, amount, '#9d735b']); renderBudget(); } });
